baseURL: https://example.com
languageCode: en-us
defaultContentLanguage: en
title: Cupper
theme: cupper-hugo-theme
enableGitInfo: true
enableEmoji: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  author: "Your name"
  iconTitle: "My site icon"
  description: An accessibility-friendly Hugo theme, ported from the [original Cupper](https://github.com/ThePacielloGroup/cupper) project.
  homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  darkThemeAsDefault: false
  hideHeaderLinks: true
  search: true
  readingTime: true
  indieauth: true
  webmentionUsername: "username.co.uk"
  maincolour: "#ff00bf"
  # A list of custom css files can be provided, which must be placed inside
  # 'static/'.
  # This is useful to override just specific css classes, instead of copying
  # the entire theme's css file to your own site.
  # Usage:
  # customCss:
  #   - css/foo.css # relative path starting from static/
  #- css/bar.css
  social:
    twitter: "TwitterName"
    gitlab: "GitLabName"
    github: "GitHubName"
    linkedin: "LinkedinName"
    email: "myemail@address.com"
    pinterest: "PinterestName"
    instagram: "InstagramName"
    reddit: "RedditSubreddit"
    slackinvite:
      name: "technottingham"
      code: "enQtNTgxNTYxMTExOTU5LTgxMDVjODUxYWI3MzNjOTJlMWUyMTYxNGEyNzYxNGYxNTExMWU0MmFkYjc5ZjI5MzY4ZmQ3MDdjZjdkNDg0ZDA"
    slackworkspace:
      name: "technottingham"
    facebook: "FacebookName"
    tiktok: "TikTokName"
    telephone: "0123456789"
    misc:
      - name: "Discord"
        url: "https://www.discord.com/"
        icon: "super-tiny-icons/discord.svg"
      - name: "YouTube"
        url: "https://youtube.com"
        icon: "super-tiny-icons/youtube.html"


menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
