#baseURL: https://vibrant-morse-7b2e84.netlify.app/
baseURL: https://blog.beachgeek.co.uk/
languageCode: en-us
defaultContentLanguage: en
title: Beachgeek blog - a refuge for pineapple on pizza lovers
theme: cupper-hugo-theme
enableGitInfo: false
enableEmoji: true
googleAnalytics: UA-160626931-1

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  author: "Ricardo Sueiras"
  iconTitle: "My site icon"
  navTitleText: Beachgeek Blog
  description: Technologist and Maker specialising in Cloud, Open Source and Innovation & Emerging Technologies.
  homeMetaContent: Technologist and Maker specialising in Cloud, Open Source and Innovation & Emerging Technologies.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). 
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  darkThemeAsDefault: false
  hideHeaderLinks: true
  search: true
  readingTime: true
  indieauth: true
  webmentionUsername: "username.co.uk"
  maincolour: "#ff00bf"
  # A list of custom css files can be provided, which must be placed inside
  # 'static/'.
  # This is useful to override just specific css classes, instead of copying
  # the entire theme's css file to your own site.
  # Usage:
  # customCss:
  #   - css/foo.css # relative path starting from static/
  #- css/bar.css
  social:
    twitter: "094459"
    github: "094459"
    linkedin: "ricardosueiras"
    email: "ricsue@amazon.com"
    reddit: "aws"

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog posts
      url: /post/
      weight: 2
    - name: Newsletter
      url: /newsletter/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4
    - name: About
      url: /about/
      weight: 5
    - name: RSS
      url: /index.xml
      weight: 6

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
